run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - durationcheck
    - errchkjson
    - exhaustive
    - gofmt

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
