name: Release

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run benchmarks
        run: go test -bench=. -benchmem ./test/...

  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    env:
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4

      - name: Run gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  # build-docker:
  #   needs: [build-and-test, security-check]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build Docker image
  #       run: |
  #         docker build -t album:${{ github.sha }} .
  #         docker tag album:${{ github.sha }} album:latest

  # Uncomment and modify if you want to push to a registry
  # - name: Login to Docker Hub
  #   uses: docker/login-action@v2
  #   with:
  #     username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     password: ${{ secrets.DOCKERHUB_TOKEN }}

  # - name: Push Docker image
  #   run: |
  #     docker push album:${{ github.sha }}
  #     docker push album:latest
